const fs = require('fs');
const lines = [];

function p(s) { lines.push(s); }

p('import * as XLSX from "xlsx";');
p('');
p('export type ParsedCbdData = {');
p('  customer: string | null; season: string | null; styleNumber: string | null;');
p('  styleName: string | null; leadTimeDays: number | null; finishWeight: string | null; moq: number | null;');
p('  yarnLines: Array<{ name: string; consumption: string; materialPrice: string; materialCost: string }>;');
p('  fabricLines: Array<{ name: string; consumption: string; materialPrice: string; materialCost: string }>;');
p('  trimLines: Array<{ name: string; consumption: string; materialPrice: string; materialCost: string }>;');
p('  knittingLines: Array<{ machineType: string; knittingTime: string; sah: string; knittingCost: string }>;');
p('  operationsLines: Array<{ operation: string; operationCost: string }>;');
p('  standardPackagingCost: number | null; specialPackagingCost: number | null;');
p('  overheadCost: number | null; profitCost: number | null; totalFactoryCost: number | null;');
p('  warnings: string[]; errors: string[];');
p('};');
p('');
p('export function parseCbdExcel(buffer: Buffer | ArrayBuffer): ParsedCbdData {');
p('  const wb = XLSX.read(buffer, { type: "buffer", cellDates: true });');
p('  const sn = wb.SheetNames[0]; if (!sn) throw new Error("No sheets");');
p('  const rows = XLSX.utils.sheet_to_json<any[]>(wb.Sheets[sn], { header: 1, defval: null });');
p('  const W: string[] = []; const E: string[] = [];');
p('  const R: ParsedCbdData = {');
p('    customer: null, season: null, styleNumber: null, styleName: null,');
p('    costedQty: null, leadTimeDays: null, finishWeight: null, moq: null,');
p('    yarnLines: [], fabricLines: [], trimLines: [], knittingLines: [], operationsLines: [],');
p('    standardPackagingCost: null, specialPackagingCost: null,');
p('    overheadCost: null, profitCost: null, totalFactoryCost: null, warnings: W, errors: E');
p('  };');
p('  const gs = (r: number, c: number): string => rows[r]?.[c] == null ? "" : String(rows[r][c]).trim();');
p('  const gn = (r: number, c: number): number | null => {');
p('    const v = rows[r]?.[c]; if (v == null) return null;');
p('    const n = Number(String(v).replace(/,/g, "")); return Number.isFinite(n) ? n : null;');
p('  };');
p('  const fsec = (kws: string[]): number => {');
p('    for (let i = 0; i < rows.length; i++) {');
p('      if (rows[i]?.some((c: any) => kws.some(kw => String(c ?? "").toLowerCase().includes(kw.toLowerCase())))) return i;');
p('    } return -1;');
p('  };');
p('  // Parse headers from first 10 rows');
p('  for (let i = 0; i < Math.min(10, rows.length); i++) {');
p('    const row = rows[i]; if (!row) continue;');
p('    for (let j = 0; j < row.length; j++) {');
p('      const cell = String(row[j] ?? "").trim();');
p('      if (cell.includes("Customer") && (cell.includes("\uff1a") || cell.includes(":"))) {');
p('        const v = gs(i, j + 1); if (v && !v.toLowerCase().includes("customer")) R.customer = v;');
p('      }');
p('      if (cell.includes("Season") && (cell.includes("\uff1a") || cell.includes(":"))) {');
p('        const v = gs(i, j + 1); if (v && !v.toLowerCase().includes("season")) R.season = v;');
p('      }');
p('      if (cell.includes("Style") && cell.includes("#")) {');
p('        const v = gs(i, j + 1); if (v && !v.toLowerCase().includes("style")) R.styleNumber = v;');
p('      }');
p('      if (cell.includes("Style Name") && cell.includes(":")) {');
p('        const v = gs(i, j + 1); if (v) R.styleName = v.replace(/\r?\n/g, " ").trim();');
p('      }');
p('      if (cell.includes("MOQ") && cell.includes(":")) {');
p('        const v = gs(i, j + 1); const m = v.match(/(\d+)/); if (m) R.moq = parseInt(m[1]);');
p('      }');
p('      if (cell.toLowerCase().includes("leadtime")) {');
p('        const v = gs(i, j + 1); const m = v.match(/(\d+)/); if (m) R.leadTimeDays = parseInt(m[1]);');
p('      }');
p('      if (cell.toLowerCase().includes("sample weight")) {');
p('        const v = gs(i, j + 1); if (v) R.finishWeight = v;');
p('      }');
p('    }');
p('  }');
p('  // Find section rows');
p('  const yH = fsec(["YARN"]), fH = fsec(["FABRIC"]), tH = fsec(["TRIM"]);');
p('  const kH = fsec(["KNITTING"]), oH = fsec(["OPERATIONS"]);');
p('  const pH = fsec(["PACKAGING"]), hH = fsec(["OVERHEAD"]), cH = fsec(["TOTAL FACTORY COST"]);');
p('  // Parse material sections: name[0], consumption[1], price[2], cost[3]');
p('  const pm = (s: number, e: number) => {');
p('    const L: Array<{name:string;consumption:string;materialPrice:string;materialCost:string}> = [];');
p('    if (s < 0) return L;');
p('    for (let i = s + 1; i < Math.min(e >= 0 ? e : s + 15, rows.length); i++) {');
p('      const fc = gs(i, 0).toLowerCase();');
p('      if (fc.includes("total") || fc.includes("sub total")) break;');
p('      const name = gs(i, 0); if (!name || name === "0") continue;');
p('      const c = gn(i, 1), pr = gn(i, 2), t = gn(i, 3);');
p('      if (c || pr || t) L.push({ name, consumption: c?.toString() ?? "", materialPrice: pr?.toString() ?? "", materialCost: t?.toString() ?? "" });');
p('    } return L;');
p('  };');
p('  if (yH >= 0) R.yarnLines = pm(yH, fH >= 0 ? fH : (tH >= 0 ? tH : (kH >= 0 ? kH : yH + 15)));');
p('  if (fH >= 0) R.fabricLines = pm(fH, tH >= 0 ? tH : (kH >= 0 ? kH : fH + 15));');
p('  if (tH >= 0) R.trimLines = pm(tH, kH >= 0 ? kH : tH + 15);');
p('  // Knitting: name[0], time[1], sah[2], cost[3]');
p('  if (kH >= 0) {');
p('    const end = oH >= 0 ? oH : kH + 15;');
p('    for (let i = kH + 1; i < Math.min(end, rows.length); i++) {');
p('      const name = gs(i, 0); if (!name || name === "0") continue;');
p('      const t = gn(i, 1), s = gn(i, 2), c = gn(i, 3);');
p('      if (t || s || c) R.knittingLines.push({');
p('        machineType: name, knittingTime: t?.toString() ?? "",');
p('        sah: s?.toString() ?? "", knittingCost: c?.toString() ?? ""');
p('      });');
p('    }');
p('  }');
p('  // Operations: name[0], cost[3]');
p('  if (oH >= 0) {');
p('    const end = pH >= 0 ? pH : oH + 20;');
p('    for (let i = oH + 1; i < Math.min(end, rows.length); i++) {');
p('      const name = gs(i, 0); if (!name || name === "0") continue;');
p('      if (name.toLowerCase().includes("sub total")) break;');
p('      const c = gn(i, 3);');
p('      if (name && c) R.operationsLines.push({ operation: name, operationCost: c.toString() });');
p('    }');
p('  }');
p('  // Packaging: name[0], cost[3]');
p('  if (pH >= 0) {');
p('    const end = hH >= 0 ? hH : pH + 10;');
p('    for (let i = pH + 1; i < Math.min(end, rows.length); i++) {');
p('      const name = gs(i, 0).toLowerCase(); const c = gn(i, 3);');
p('      if (name.includes("standard") && c != null) R.standardPackagingCost = c;');
p('      else if (name.includes("special") && c != null) R.specialPackagingCost = c;');
p('    }');
p('  }');
p('  // Overhead/Profit: name[0], cost[3]');
p('  if (hH >= 0) {');
p('    const end = cH >= 0 ? cH : hH + 10;');
p('    for (let i = hH + 1; i < Math.min(end, rows.length); i++) {');
p('      const name = gs(i, 0).toLowerCase(); const c = gn(i, 3);');
p('      if (name.includes("overhead") && c != null) R.overheadCost = c;');
p('      else if (name.includes("profit") && c != null) R.profitCost = c;');
p('    }');
p('  }');
p('  if (cH >= 0) R.totalFactoryCost = gn(cH, 3);');
p('  if (!R.customer) W.push("Customer not found in Excel");');
p('  if (!R.styleNumber) W.push("Style number not found in Excel");');
p('  if (R.yarnLines.length === 0) W.push("No yarn lines found");');
p('  if (R.knittingLines.length === 0) W.push("No knitting lines found");');
p('  if (R.operationsLines.length === 0) W.push("No operations found");');
p('  return R;');
p('}');
p('');
p('export function validateParsedCbd(data: ParsedCbdData) {');
p('  const errors: string[] = [];');
p('  if (!data.customer) errors.push("Customer is required");');
p('  if (!data.styleNumber) errors.push("Style number is required");');
p('  if (data.yarnLines.length === 0 && data.fabricLines.length === 0 && data.trimLines.length === 0)');
p('    errors.push("At least one 
